#!/bin/bash

NAMES=("mongodb" "redis" "mysql" "rabbitmq" "catalogue" "user" "cart" "shipping" "payment" "dispatch" "web")
INSTANCE_TYPE=t2.micro
IMAGE_ID=ami-03265a0778a880afb
SECURITY_GROUP_ID=sg-0f57d02eee766b7c1
DOMAIN_NAME=shivalearning.online
# if mysql or mongodb instance_type should be t3.medium , for all others it is t2.micro

for i in "${NAMES[@]}"
do  
   echo "creating $i instance"
   aws ec2 run-instance --image-id $IMAGE_ID --instance-type $INSTANCE_TYPE --security-group 
   $SECURITY_GROUP_ID --tag-specifications  "ResourceType=instance,Tags=[{Key=Name,Value=$i}]"
done